version: "3.8"
services:
  # db_server:
  #   container_name: postgres_container
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: root  
  #     POSTGRES_PASSWORD: root
  #   volumes:
  #     - type: bind
  #       source: ~/Desktop/postgres_test/pgdata/primary
  #       target: /var/lib/postgresql/data
  #       bind:
  #         create_host_path: true
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     test_network: 
  #       ipv4_address: 172.27.0.2
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   volumes:
  #     - type: bind
  #       source: ~/Desktop/postgres_test/pgadmin_data
  #       target: /var/lib/pgadmin
  #       bind:
  #         create_host_path: true
  #   ports:
  #     - "5050:80"
  #   networks:
  #     test_network: 
  #       ipv4_address: 172.27.0.3
  test:
    container_name: test
    image: base-image:latest
    volumes:
      - type: bind
        source: ~/Desktop/postgres_test/src
        target: /usr/app/postgres_ws
        bind:
          create_host_path: true
      - type: bind
        source: ~/Desktop/postgres_test/fastdds_ws
        target: /usr/app/fastdds_ws
        bind:
          create_host_path: true
    stdin_open: true
    tty: true
    networks:
      test_network: 
        ipv4_address: 172.27.0.4

networks:
  test_network:
    name: postgres-test
    driver: bridge
    ipam:
      config:
        - subnet: "172.27.0.0/16"
          gateway: "172.27.0.1"
