install:
	pipenv install

run-cache:
	pipenv run python cache.py

run-lru_cache:
	pipenv run python lru_cache.py

run-partial:
	pipenv run python partial.py

run-reduce:
	pipenv run python reduce.py

run-singledispach:
	pipenv run python singledispach.py